# Generated by Django 4.0.6 on 2022-08-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=models.TextField(max_length=400),
        ),
    ]
